### ISSUE TITLE
Run the GH tests also on Mac

### ISSUE THREAD

**Issue by dirkschumacher** [nextmv-io/go-routingkit#28]
The current GH workflow runs the go-tests on Ubuntu. It would make sense to also run the workflow on an intel Mac as well, as we provide precompiled, platform specific binaries.

https://github.com/nextmv-io/go-routingkit/blob/8f7deb843e08a7928faaf54edc2758c5e991d2e6/.github/workflows/go-routingkit-test.yml#L7

Solution is to add a matrix strategy like this:

```
build:
  ...
  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest]
  runs-on: ${{ matrix.os }}
```
